name: CI
on: [push, pull_request]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        pg:
          - 18
          - 17
          - 16
          - 15
          - 14
          # versions before 14 no not support Infinity in numeric and lack lz4 support
          - 13
          - 12
          # versions before 12 have a different output format for floats (inf/Infinity, nan/NaN)
          - 11
          - 10

    name: 🐘 PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container:
      image: pgxn/pgxn-tools
      options: -e AS_USER=postgres

    steps:
      - name: Start PostgreSQL ${{ matrix.pg }}
        run: pg-start ${{ matrix.pg }}
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Give build directory to postgres
        run: 'chown -R postgres: .'
      - name: Install extra build dependencies
        run: apt-get install -y liblz4-dev libipc-run-perl
      - name: Build and test on PostgreSQL ${{ matrix.pg }}
        run: sudo -u postgres pg-build-test
