name: CI
on: [push, pull_request]

jobs:
  test:

    strategy:
      matrix:
        pg:
          - 16
          - 15
          - 14
          # versions before 14 no not support Infinity in numeric
          - 13
          - 12
          # versions before 12 have a different output format for floats (inf/Infinity, nan/NaN)
          - 11
          - 10

    name: 🐘 PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools

    steps:
      - name: Start PostgreSQL ${{ matrix.pg }}
        run: pg-start ${{ matrix.pg }}
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install extra build dependencies
        run: sudo apt-get install -y liblz4-dev
      - name: Build and test on PostgreSQL ${{ matrix.pg }}
        run: PATH=$PATH:/usr/lib/postgresql/${{ matrix.pg }}/bin pg-build-test
